"use client";

import { useState } from "react";

type PatternRecognitionProps = {
  userData: any;
};

type Pattern = {
  id: string;
  type: "strength" | "challenge" | "drift" | "growth";
  title: string;
  description: string;
  evidence: string[];
  frequency: number;
  trend: "increasing" | "stable" | "decreasing";
  relatedDomains: string[];
  recommendation?: string;
};

export default function PatternRecognition({ userData }: PatternRecognitionProps) {
  const [selectedPattern, setSelectedPattern] = useState<Pattern | null>(null);
  const [filterType, setFilterType] = useState<string | null>(null);

  // Mock patterns - will be generated by AI from database
  const patterns: Pattern[] = [
    {
      id: "1",
      type: "strength",
      title: "Multi-party coordination mastery",
      description: "You consistently excel in settings with multiple stakeholders and competing communication needs. Your ability to maintain neutrality while ensuring all parties are heard has improved 35% over the past 3 months.",
      evidence: [
        "8 successful IEP meetings with positive feedback",
        "Family conference coordination in medical settings",
        "Multi-party VRI sessions with minimal confusion"
      ],
      frequency: 12,
      trend: "increasing",
      relatedDomains: ["Education", "Medical", "Legal"],
      recommendation: "Consider seeking advanced certifications in conference interpreting or mediation settings."
    },
    {
      id: "2",
      type: "challenge",
      title: "Legal vocabulary retention difficulty",
      description: "Pattern identified: Legal terminology retention is 18% lower than other domains. You frequently need to reference materials during depositions and court proceedings.",
      evidence: [
        "3 instances of term look-ups during legal assignments",
        "Self-reported uncertainty in deposition prep notes",
        "Lower confidence ratings in legal debriefs (avg 6.2/10 vs 8.4/10 in medical)"
      ],
      frequency: 8,
      trend: "stable",
      relatedDomains: ["Legal"],
      recommendation: "Schedule focused legal terminology review sessions. Consider creating flashcard sets for frequently encountered legal contexts."
    },
    {
      id: "3",
      type: "drift",
      title: "Wednesday double-block pattern",
      description: "Burnout signals consistently spike on Wednesdays when you have back-to-back assignments. Recovery time metrics show 40% slower emotional rebound on these days.",
      evidence: [
        "4 out of 5 Wednesdays show elevated stress markers",
        "Sleep quality drops to 'poor' after Wednesday doubles",
        "Emotional intensity ratings 2.1 points higher than average"
      ],
      frequency: 5,
      trend: "increasing",
      relatedDomains: ["Medical", "Education"],
      recommendation: "Request scheduling adjustment: block Thursday mornings for recovery after Wednesday doubles. Consider limiting Wednesday assignments to single sessions."
    },
    {
      id: "4",
      type: "growth",
      title: "Cardiology terminology acceleration",
      description: "Your medical vocabulary has improved 22% over the past month, with exceptional growth in cardiology-specific terminology. Pattern shows accelerated learning curve.",
      evidence: [
        "Confidence ratings in cardiology sessions up from 6.5 to 8.8",
        "Zero term look-ups in last 3 cardiology assignments",
        "Provider feedback mentioned 'seamless technical communication'"
      ],
      frequency: 7,
      trend: "increasing",
      relatedDomains: ["Medical"],
      recommendation: "Your learning pattern suggests you excel with repeated exposure. Consider requesting more cardiology assignments to capitalize on momentum."
    }
  ];

  const filteredPatterns = filterType
    ? patterns.filter(p => p.type === filterType)
    : patterns;

  const getPatternColor = (type: string) => {
    switch (type) {
      case "strength":
        return {
          bg: "bg-emerald-500/10",
          border: "border-emerald-500/30",
          text: "text-emerald-300",
          icon: "✓"
        };
      case "challenge":
        return {
          bg: "bg-amber-500/10",
          border: "border-amber-500/30",
          text: "text-amber-300",
          icon: "⚠"
        };
      case "drift":
        return {
          bg: "bg-red-500/10",
          border: "border-red-500/30",
          text: "text-red-300",
          icon: "↓"
        };
      case "growth":
        return {
          bg: "bg-teal-500/10",
          border: "border-teal-500/30",
          text: "text-teal-300",
          icon: "↑"
        };
      default:
        return {
          bg: "bg-slate-500/10",
          border: "border-slate-500/30",
          text: "text-slate-300",
          icon: "•"
        };
    }
  };

  const getTrendIcon = (trend: string) => {
    switch (trend) {
      case "increasing":
        return "↗";
      case "decreasing":
        return "↘";
      case "stable":
        return "→";
      default:
        return "→";
    }
  };

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-semibold text-slate-50">Pattern Recognition</h2>
          <p className="text-sm text-slate-400 mt-1">Cross-assignment insights from Elya</p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-violet-500/10 border border-violet-500/30">
          <div className="w-2 h-2 rounded-full bg-violet-400 animate-pulse" />
          <p className="text-xs font-medium text-violet-300">AI Active</p>
        </div>
      </div>

      {/* Filter Buttons */}
      <div className="mb-6 flex flex-wrap gap-2">
        <button
          onClick={() => setFilterType(null)}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
            filterType === null
              ? "bg-teal-500/20 text-teal-300 border border-teal-500/30"
              : "bg-slate-800/50 text-slate-400 hover:text-slate-300 border border-slate-700"
          }`}
        >
          All Patterns ({patterns.length})
        </button>
        <button
          onClick={() => setFilterType("strength")}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
            filterType === "strength"
              ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30"
              : "bg-slate-800/50 text-slate-400 hover:text-slate-300 border border-slate-700"
          }`}
        >
          Strengths
        </button>
        <button
          onClick={() => setFilterType("growth")}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
            filterType === "growth"
              ? "bg-teal-500/20 text-teal-300 border border-teal-500/30"
              : "bg-slate-800/50 text-slate-400 hover:text-slate-300 border border-slate-700"
          }`}
        >
          Growth
        </button>
        <button
          onClick={() => setFilterType("challenge")}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
            filterType === "challenge"
              ? "bg-amber-500/20 text-amber-300 border border-amber-500/30"
              : "bg-slate-800/50 text-slate-400 hover:text-slate-300 border border-slate-700"
          }`}
        >
          Challenges
        </button>
        <button
          onClick={() => setFilterType("drift")}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
            filterType === "drift"
              ? "bg-red-500/20 text-red-300 border border-red-500/30"
              : "bg-slate-800/50 text-slate-400 hover:text-slate-300 border border-slate-700"
          }`}
        >
          Drift Signals
        </button>
      </div>

      {/* Pattern Cards */}
      <div className="space-y-3">
        {filteredPatterns.map((pattern) => {
          const colors = getPatternColor(pattern.type);

          return (
            <div
              key={pattern.id}
              className={`rounded-xl border ${colors.border} ${colors.bg} p-5 hover:bg-opacity-20 transition-all cursor-pointer`}
              onClick={() => setSelectedPattern(selectedPattern?.id === pattern.id ? null : pattern)}
            >
              {/* Header */}
              <div className="flex items-start justify-between gap-3 mb-3">
                <div className="flex items-start gap-3 flex-1">
                  <div className={`w-8 h-8 rounded-lg ${colors.bg} border ${colors.border} flex items-center justify-center flex-shrink-0`}>
                    <span className={`text-lg ${colors.text}`}>{colors.icon}</span>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="text-base font-semibold text-slate-200">{pattern.title}</h3>
                      <span className="text-xs text-slate-500">
                        {getTrendIcon(pattern.trend)} {pattern.trend}
                      </span>
                    </div>
                    <p className="text-sm text-slate-400 capitalize">{pattern.type} pattern • {pattern.frequency} occurrences</p>
                  </div>
                </div>
                <svg
                  className={`w-5 h-5 text-slate-400 transition-transform ${selectedPattern?.id === pattern.id ? 'rotate-180' : ''}`}
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
              </div>

              {/* Description */}
              <p className="text-sm text-slate-300 leading-relaxed mb-3">{pattern.description}</p>

              {/* Domains */}
              <div className="flex flex-wrap gap-1.5 mb-3">
                {pattern.relatedDomains.map((domain) => (
                  <span
                    key={domain}
                    className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-slate-800/50 text-slate-400 border border-slate-700"
                  >
                    {domain}
                  </span>
                ))}
              </div>

              {/* Expanded Details */}
              {selectedPattern?.id === pattern.id && (
                <div className="mt-4 pt-4 border-t border-slate-800 space-y-4">
                  {/* Evidence */}
                  <div>
                    <p className="text-xs text-slate-400 uppercase tracking-wide mb-2">Evidence</p>
                    <ul className="space-y-1.5">
                      {pattern.evidence.map((item, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-sm text-slate-300">
                          <span className={`h-1.5 w-1.5 rounded-full ${colors.text.replace('text-', 'bg-')} mt-1.5 flex-shrink-0`} />
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Recommendation */}
                  {pattern.recommendation && (
                    <div className="p-3 rounded-lg bg-violet-500/5 border border-violet-500/20">
                      <p className="text-xs text-violet-400/80 uppercase tracking-wide mb-1">Elya's Recommendation</p>
                      <p className="text-sm text-slate-300">{pattern.recommendation}</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {filteredPatterns.length === 0 && (
        <div className="text-center py-8 text-slate-500">
          <p>No patterns found for this filter</p>
        </div>
      )}
    </div>
  );
}
